name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Build
      run: cd next_prime_finder && cargo build --verbose

    - name: Run tests
      run: cd next_prime_finder && cargo test --verbose

    - name: Check formatting
      run: cd next_prime_finder && cargo fmt -- --check

    - name: Run Clippy
      run: cd next_prime_finder && cargo clippy -- -D warnings
